[package]
name = "arg_combinators"
description = "Command line argument combinators"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/arg-combinators.git"
repository = "https://github.com/stevebob/arg-combinators.git"
documentation = "https://docs.rs/arg-combinators"

[dependencies]
getopts = "0.2"
either = "1.5"
