[package]
name = "argle"
description = "Argument parsing library"
version = "0.0.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/argle.git"
repository = "https://github.com/stevebob/argle.git"
documentation = "https://docs.rs/argle"

[dependencies]
getopts = "0.2"
either = "1.5"
