[package]
name = "argle"
description = "Command line argument combinator library"
version = "0.1.1"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/argle.git"
repository = "https://github.com/stevebob/argle.git"
documentation = "https://docs.rs/argle"

[dependencies]
getopts = "0.2"
either = "1.5"
